name: async_resource
description: Automatically cache network resources and use them when offline. Interface with local resources on any platform.
version: 0.1.2
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/async_resource

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.11.3+17
  meta: ^1.1.6
  path: ^1.6.2
  service_worker: ^0.2.3
  rxdart: ^0.18.1

dev_dependencies:
  mockito: ^3.0.0
  test: ^1.3.0
