name: async_resource
description: Automatically cache network resources and use them when offline. Interface with local resources on any platform.
version: 0.1.2
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/async_resource

dependencies:
  http: ^0.11.3+16
  meta: ^1.1.5
  path: ^1.6.1
  service_worker: ^0.2.2

dev_dependencies:
  mockito: ^3.0.0-beta+3
  test: ^1.3.0

environment:
  sdk: ">=1.19.0 <3.0.0"