name: async_resource_example
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jacob Phillips <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async_resource:
    # path: ../../..
  json_annotation: ^1.2.0
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.3
  build_runner: ^0.10.3
  json_serializable: ^1.4.0